feat(Subtopics) EVAL-330 : Added Subtopic CRUD
OPEN-ENT-NG/competences pull request #103
Opened 2022-08-10 13:14 UTC by FlorentMr

## Describe your changes
Added the notion of subtopics coefficient and Subtopic items to setup future changes to give the possibility to calculate averages of subtopics with chosen coefficient (such as having written notes be valued twice as much as oral notes). Also let the users (with permission) change those subtopics coefficient on Vie Scolaire (cf ticket).

## Checklist tests

## Issue ticket number and link
https://jira.support-ent.fr/browse/EVAL-330

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-11 16:00 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/SubTopicController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Est ce que c'est suffisent comme sécurité ? Cela veux dire que j'ai juste besoin d'etre connecter pour modifier le coeff avec l'id 10 ?

2022-08-11 16:01 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/SubTopicService.java
> +    void getSubtopicServices(String idStructure,String idClasse, Handler<Either<String, JsonArray>> defaultResponseHandler);
Peut tu utiliser des futures ? Ce sera plus simple a manipuler (compose, indentation etc...)

2022-08-11 16:20 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/SubTopicController.java
> +        RequestUtils.bodyToJson(request, body ->{
Tu peux utiliser `bodyToJson(final HttpServerRequest request, final String schema, final Handler<JsonObject> handler)`
exemple
`RequestUtils.bodyToJson(request, pathPrefix + "alertDelete", body -> {}`

https://github.com/OPEN-ENT-NG/presences/blob/MA-770/presences/src/main/resources/jsonschema/alertDelete.json

2022-08-11 16:22 UTC, BastienBenard commented on src/main/java/fr/openent/competences/model/Matiere.java
> -import io.vertx.core.json.Json;
Tu le supp car ce n'est pas utilisé ?

2022-08-11 16:27 UTC, BastienBenard commented on src/main/java/fr/openent/competences/model/SubTopic.java
> +                .put("coefficient",coefficient);
Magic string

2022-08-11 16:28 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +        subTopicService = new DefaultSubTopicService(Competences.COMPETENCES_SCHEMA, "services_subtopic");
Tu peux utiliser une constant comme pour  Competences.NOTES_TABLE

2022-08-11 16:28 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +        subTopicService = new DefaultSubTopicService(Competences.COMPETENCES_SCHEMA, "services_subtopic");
Tu peux utiliser une constant comme pour Competences.NOTES_TABLE

2022-08-11 16:29 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                    sousMat.put("subCoef",1);
Magic string

2022-08-11 16:30 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                                sousMat.put("subCoef",subTopic.getCoefficient());
Tu peut utiliser un stream + filter. Magic String

2022-08-11 16:31 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +        buildSousMatieres(matiereJO, tableauDeconversion, idPeriode , params,services);
indentation

2022-08-11 16:31 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                        getSubTopicCoeff(firstStudent.getString("idEtablissement"),firstStudent.getString("idClasse"),subTopicCoefPromise);
magic string + indentation

2022-08-11 16:32 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                            setServices(structure, servicesJson, services,subTopics);
indentation

2022-08-11 16:34 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                    subTopic.setCoefficient(safeGetDouble(subTopicJo,"coefficient"));
Magic String

2022-08-11 16:35 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +            }
stream + filter

2022-08-11 16:35 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +
ce n'est pas utile

2022-08-11 16:36 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +                .stream().map(group -> ((JsonObject)group).getString("id")).collect(Collectors.toList());
Magic String

2022-08-11 16:37 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +        }
for each + indentation

2022-08-11 16:39 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +                .put("action", "prepared");
Magic String

2022-08-12 07:17 UTC, BastienBenard commented on src/main/resources/public/ts/models/common/ServiceSnipplet.ts
> +                        console.log("plop")
Plop ? ^^

2022-08-12 07:23 UTC, BastienBenard commented on src/main/resources/public/ts/sniplets/paramServices.ts
>                          paramServices.that.subTopics.all.map(sb => {
Tu fait un map mais tu ne récupère pas le résultat. Ce serait plutot un for each.

2022-08-12 07:30 UTC, BastienBenard commented on src/main/resources/public/ts/sniplets/paramServices.ts
> +                            let sbt =  paramServices.that.subTopicsServices.all.find(subTopicsService =>{
typage

2022-08-12 07:34 UTC, BastienBenard commented on src/main/resources/public/ts/models/sniplets/SubTopicsService.ts
> +        this.coefficient = parseFloat(data.coefficient);
si ton parseFloat fail, coefficient va etre null. Est ce que c'est voulu ?

2022-08-12 07:35 UTC, BastienBenard commented on src/main/resources/public/ts/models/sniplets/SubTopicsService.ts
> +            let sts =  new SubTopicsService();
typage

2022-08-12 07:35 UTC, BastienBenard commented on src/main/resources/public/ts/sniplets/paramServices.ts
> +                                 }else{
indentation

2022-08-19 07:13 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/SubTopicController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Ca ne posera pas de problème je pense

2022-08-19 07:14 UTC, Rseuret commented on src/main/java/fr/openent/competences/model/Matiere.java
> -import io.vertx.core.json.Json;
Oui

2022-08-30 07:36 UTC, JinDouang requested changes

2022-08-30 07:36 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                    }
Si je comprends bien, tu boucles pour chaque service, tu récupères une liste de subtopic et tu l'itères pour comparer avec ton id ?

Voici ma suggestion en utilisant les streams et flatMap : 
```suggestion
                   services.stream()
                            .map(Service::getSubtopics)
                            .flatMap(Collection::stream)
                            .forEach(subTopic -> {
                                if(subTopic.getId().equals(sousMat.getInteger("id_type_sousmatiere"))){
                                    sousMat.put(Field.SUBCOEF,subTopic.getCoefficient());
                                }
                            });
```

Tu streams ton services que tu vas mapper, ensuite tu flatMap chaque liste qu'il y a (donc le subtopic) et tu boucles dessus pour faire ta comparaison!

(si ca marche pas on voit ensemble mais l'idée est là)

2022-08-30 07:36 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> +                    }
magic string "id_type_sousmatiere"

2022-08-30 07:36 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +            statements.add(setStatementCoefficient(data,idGroup));
Si tu n'as qu'une ligne, tu peux enlever les bracket (un peu comme tu as fait au dessus)

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/models/sniplets/SubTopicsService.ts
> +let subTopicsServiceService = new SubTopicsServiceService();
Tu n'as pas besoin de faire ça pour ton appel (voir en dessous)

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/models/sniplets/SubTopicsService.ts
> +    async get(idStructure) {
Si tu fais un await get dessus, il vaut mieux que tu fasses un set dans laquelle tu mets le résultat de ton await pour que ton get (ou en utilisant ton this.all) soit au final une récupération (ta déclaration que tu avais fait au-dessus, sa place serait mieux dans un controller/sniplet pour ton business logic

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/services/SubTopicServiceService.ts
> +}
Rajoutes aussi la possibilté d'être injécté par le service d'angular : 

`export const subTopicService = ng.service('SubTopicService', SubTopicsServiceService);` à la fin

Ca permet au controller/directive de pouvoir s'injecter directement le service plutôt que de l'instancier

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/services/SubTopicServiceService.ts
> +    }
Typage : 

```suggestion
    async set(subTopicsService: SubTopicsService): Promise<AxiosResponse> {
       return http.post(`competences/subtopics/services/update`, subTopicsService.toJson());
    }
```

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/services/SubTopicServiceService.ts
> +    }
Typage : 

```suggestion
   async get(idStructure): Promise<AxiosResponse> {
      return http.get(`/competences/subtopics/services/${idStructure}`);
    }
```

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/services/SubTopicServiceService.ts
> +}
et n'oublie pas l'import !  
`import {ng} from "entcore"`

2022-08-30 07:36 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/paramServices.ts
> +            this.subTopicsServices = new SubTopicsServices([])
il manque le ";" à la fin 😄

2022-08-30 08:08 UTC, JinDouang requested changes

2022-08-30 08:08 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/SubTopicController.java
> +    @ApiDoc("set SubtopicsServices")
Si tu as fait de nouvelles API, faudrait que tu la documentes et que tu mettes ton lien dans la description: 

_"I have made corresponding changes to the documentation (API Doc etc...) - (must specify in Description for target version)_"

2022-08-31 12:40 UTC, lapeyronnie commented
Penser à ajouter la documentation sur les nouvelle API.

2022-09-01 07:25 UTC, JinDouang commented on src/main/resources/public/ts/services/SubTopicServiceService.ts
> +import http from "axios";
subtopicservice.service.ts

2022-09-02 08:34 UTC, merged