feat():EVAL-334 snipplet to choose the caculation of skill items
OPEN-ENT-NG/competences pull request #110
Opened 2022-08-24 15:17 UTC by lapeyronnie

## Describe your changes
ajout d'une snipplet pour choisir le clacul des items de compétences : moyenne -> true, max -> false (valeur par défaut)
L'application sera faite dans une branche. Cette PR est liée à la PR de viscolaire sur la branche MSV-73
## Checklist tests

## Issue ticket number and link
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
[MVS-73](https://jira.support-ent.fr/browse/MVS-73)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-26 11:51 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/StructureOptionsController.java
> +        return !body.containsKey("structure_id") && !body.containsKey("is_average_skills");
Utiliser des contantes . Pourquoi parfois "structure_id" et parfois "structureId"

2022-08-26 11:51 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultStructureOptions.java
> +        final boolean isAverageSkills = body.getBoolean("is_average_skills");
constante : Magic string

2022-08-31 16:25 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/constants/Field.java
> +            "eval_createOrUpdateStructureOptionIsAverageSkills";
les schéma json seront mis ici dorénavant

2022-09-01 07:41 UTC, JinDouang requested changes

2022-09-01 07:41 UTC, JinDouang commented on src/main/resources/public/ts/services/structureOptions.ts
> +import {ng} from 'entcore'
structure-options.service.ts

2022-09-01 07:41 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts
> +            let option = await structureOptionsService.getStructureOptionsIsAverageSkills(structureId);
Tu peux le faire en une ligne non ?
```suggestion
      this.option = await structureOptionsService.getStructureOptionsIsAverageSkills(structureId);
```

2022-09-01 07:41 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts
> +            let option = await structureOptionsService.getStructureOptionsIsAverageSkills(structureId);
Attention au typage!

2022-09-01 07:41 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts
> +            await structureOptionsService.saveStrustureOptinsIsAverageSkills(this.option)
attention au ; à la fin!

2022-09-05 06:29 UTC, JinDouang approved these changes

2022-09-05 06:34 UTC, JinDouang approved these changes

2022-09-05 06:34 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts
> +    async initOptionsIsAverageSkills(structureId: String): Promise<void> {
Il faudrait éviter l'usage de l'objet String et plutôt utiliser primitive `string`

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

2022-09-05 06:34 UTC, JinDouang commented on src/main/resources/public/ts/services/structure-options.service.ts
> +            const response = await http.get(`competences/structure/${structureId}/options/isSkillAverage`);
typage response

```suggestion
 const response: AxiosResponse = await http.get(`competences/structure/${structureId}/options/isSkillAverage`);
```

2022-09-05 06:35 UTC, JinDouang requested changes

2022-09-05 06:35 UTC, JinDouang commented on src/main/resources/public/ts/sniplets/structure-option-is-average-skills.ts
> +    async initOptionsIsAverageSkills(structureId: String): Promise<void> {
Il faudrait éviter l'usage de l'objet String et plutôt utiliser primitive string

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

2022-09-05 06:35 UTC, JinDouang commented on src/main/resources/public/ts/services/structure-options.service.ts
> +            const response = await http.get(`competences/structure/${structureId}/options/isSkillAverage`);
typage response

```suggestion
 const response: AxiosResponse = await http.get(`competences/structure/${structureId}/options/isSkillAverage`);
```

2022-09-05 08:10 UTC, JinDouang approved these changes

2022-09-27 13:32 UTC, merged