EVAL-334 application skill average on all  BFC (exportpdf BFC + LSU a…
OPEN-ENT-NG/competences pull request #113
Opened 2022-08-30 06:19 UTC by lapeyronnie

## Describe your changes
application de l'option moyenne des items de competences sur l'export BFC, LSU et onglet du positionnement dans le suivi classe.
refacto class java competenceNote
## Checklist tests
suivi classe onglet positionnement, export Bfc et LSU BFC
create, update, delete competenceNote, écran releve périodique (détail élève et graphe), conseil de classe, suivi élève.
## Issue ticket number and link
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-02 13:02 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +    private void callCompetencesNotesService(List<String> idEleves, Long idPeriode, Boolean isSkillAverage, HttpServerRequest request) {
aux vu de la manière dont tu te sers de "isSkillAverage", ce ne serait pas possible de le typer en primitif plutôt ?
pareil pour idPeriode ?

2022-09-02 13:03 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/CompetenceNoteService.java
> +    void getMaxOrAverageCompetenceNoteEleveByPeriod (String[] idEleves, Long idPeriode, Boolean isYear, Boolean isSkillAverage,
primitive pour ton long et tes booleans ?

2022-09-02 13:03 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/CompetenceNoteService.java
> +    void getMaxOrAverageCompetencesNotesClasse(List<String> idEleves, Long idPeriode, Boolean isSkillAverage,
primitives pour ton long et tes booleans ?

2022-09-05 08:10 UTC, JinDouang requested changes

2022-09-06 11:33 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> -    }
cette API n'est pas utilisée ni dans competence, ni dans viescolaire

2022-09-06 11:35 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                }
supprimé car seulement utilsée pa rAPI qui a été supprimée

2022-09-06 11:35 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> -
non utilisé

2022-09-06 11:54 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultCompetenceNoteService.java
> +                    mapOrdreBareme.put(nivCompetence.getInteger("ordre"),nivCompetence.getInteger("bareme_brevet"));
pour une prochaine fois car hors du périmétre et délai

2022-09-06 11:55 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/CompetenceNoteService.java
> +    void getMaxOrAverageCompetencesNotesClasse(List<String> idEleves, Long idPeriode, Boolean isSkillAverage,
Je fais le choix de garder l'object

2022-09-06 11:55 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/CompetenceNoteService.java
> +    void getMaxOrAverageCompetenceNoteEleveByPeriod (String[] idEleves, Long idPeriode, Boolean isYear, Boolean isSkillAverage,
Je fais le choix de garder l'object

2022-09-06 11:56 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +    private void callCompetencesNotesService(List<String> idEleves, Long idPeriode, Boolean isSkillAverage, HttpServerRequest request) {
je fais le choix de garder l'object

2022-09-06 12:03 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/CompetenceNoteService.java
> +    void getMaxOrAverageCompetencesNotesClasse(List<String> idEleves, Long idPeriode, Boolean isSkillAverage,
Yes, je suis d'accord, autant à l'arriver dans un Controller, on peut les recevoir en primitive, mais un service pouvant être générique et appelé a plusieurs endroits, les params peuvent être des objets pour plus de flexibilité.

2022-09-06 12:04 UTC, qpic-cgi approved these changes

2022-09-06 13:26 UTC, JinDouang requested changes

2022-09-06 13:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                    JsonObject error = (new JsonObject()).put("error", (String)event.left().getValue());
Tu as des parenthèses redondantes tu pourrais faire ça : 

```suggestion
    JsonObject error = new JsonObject().put("error", event.left().getValue());
```
Et gérer le magic string "error" si possible!

2022-09-06 13:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                       competenceNoteEleve.put("evaluation", evaluation);
magic string "evaluation"

2022-09-06 13:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                    Renders.renderJson(request, error);
c'est voulu de faire un renderJson face à un cas d'erreur ?
Car tu pourrais utiliser renderError à la place

De plus, tu ne fais pas de return donc le traitement continuera et tu risques d'avoir des erreurs "Request has already been read"

2022-09-06 13:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                List<String> idEleves = new ArrayList<String>();
Pas besoin de préciser le typage de ton ArrayList

```suggestion
                List<String> idEleves = new ArrayList<>();
```
source: https://sonarsource.atlassian.net/browse/RSPEC-2293#:~:text=Java%207%20introduced%20the%20diamond,compiler%20will%20infer%20the%20type.

2022-09-06 13:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> +                        Renders.notFound(request,"Impossible de recuperer le type de calcul des competences notes \n"
Attention tu envoies une erreur "not found" mais comme tu return pas, il continuera le traitement et tu te risques à une erreur de http

2022-09-06 14:36 UTC, JinDouang approved these changes

2022-09-23 06:14 UTC, merged