feat: Eval 334 apply option Skill Average to student follow-up
OPEN-ENT-NG/competences pull request #114
Opened 2022-08-31 16:02 UTC by lapeyronnie

## Describe your changes
appliquer la moyenne des items de compétences dans le suivi élève dans les méthodes getMaxEvaluations dans eval_suivi_competences_classe_ctl.ts et setMaxCompetenceShow  dans Utils et eval_suivi_eleve_ctl.ts
## Checklist tests
suivi élève onglet suivi des items et icône BFC pour toutes les périodes, pour un multi établissement
## Issue ticket number and link
[EVAL-334](https://jira.support-ent.fr/browse/EVAL-334)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-31 16:21 UTC, BastienBenard commented on src/main/resources/public/ts/utils/functions/average.ts
> +    },  0) / (arr.length === 0 ? 1 : arr.length);
Cette espace ne me semble pas utile

2022-08-31 16:22 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +        $scope.getMaxOrAverageEvaluations = function (idEleve) {
typage de retour

2022-08-31 16:23 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +            let evals = _.where($scope.detailCompetence.competencesEvaluations, {id_eleve: idEleve});
typage de evals

2022-08-31 16:24 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +                    Utils.getNiveauMaxOfListEval(evals,$scope.suiviCompetence.tableauConversion,false,
espace apres les ,

2022-08-31 16:24 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +        $scope.FilterColor = (item) => {
typage de item

2022-08-31 16:24 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts
> +                Utils.setMaxOrAverageCompetenceShow(competence, $scope.suiviCompetence.tableConversions, isYear,false,$scope.listTeacher);
espace entre les ,

2022-08-31 16:25 UTC, BastienBenard commented on src/main/resources/public/ts/models/teacher/Structure.ts
> +        structureOptionsService.getStructureOptionsIsAverageSkills(that.id).then(res =>{
typage res + Il ne faudrait pas un catch en cas d'échec ?

2022-08-31 16:26 UTC, BastienBenard commented on src/main/resources/public/ts/models/teacher/Utils.ts
> +            let niveauFinalToShowMyEvaluations = (evaluations.structure.options.isSkillAverage) ?
typage niveauFinalToShowMyEvaluations

2022-08-31 16:27 UTC, BastienBenard commented on src/main/resources/public/ts/models/teacher/Utils.ts
> +    static getNiveauMoyOfListEval (listEval, tableConversion, onlyNote?, isYear?){
typage params et retour

2022-09-01 08:01 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/Structure.ts
> +        structureOptionsService.getStructureOptionsIsAverageSkills(that.id).then(res =>{
Vu l'état des autres services qui n'ont pas cette gestion je pense que même mettre un catch ne changerait pas grand chose au final 
C'est pas bien grave dans ce cas (le jour où on voudra agir sur les échecs des calls API on en rediscutera)

2022-09-01 08:04 UTC, JinDouang requested changes

2022-09-01 08:04 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/Structure.ts
> +import {StructureOptions, structureOptionsService, StructureOptionsService} from "../../services";
StructureOptionsService n'est pas utilisé

2022-09-02 12:18 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +                evals = _.filter(evals,evaluation => {
typage des params tu filter, si possible

2022-09-02 12:18 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +                evals = _.filter(evals, function (competence) {
typage des params tu filter, si possible

2022-09-02 12:20 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +                evals = _.filter(evals,evaluation => {
typage de evaluation, si possible

2022-09-02 13:05 UTC, lapeyronnie commented on src/main/resources/public/ts/models/teacher/Utils.ts
> +                _.map(poDomaine.competences.all, async function (competence) {
En effet, ce n'est pas nécessaire, c'est oubli.

2022-09-06 07:21 UTC, JinDouang approved these changes

2022-09-08 09:13 UTC, merged