eval-331 : moyenne releve periodique
OPEN-ENT-NG/competences pull request #116
Opened 2022-09-07 09:27 UTC by FlorentMr

## Describe your changes
Releve Periodique averages are now being calculated by taking in account subtopics coefficients. 

## Checklist tests
Relevé périodique -> Chose a group+period+topic -> Check Moy Auto + Moy Finale. Can also check details by clicking on the 
pencil on the right of a line.

## Issue ticket number and link
[EVAL-331](https://jira.support-ent.fr/browse/EVAL-331)
Parent ticket : [EVAL-139](https://jira.support-ent.fr/browse/EVAL-139)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-07 09:43 UTC, BastienBenard commented on src/main/java/fr/openent/competences/bean/StatMat.java
> +                        statClass.putSousMatiereMapEleveStat(note.getString("id_eleve"), sousMatiereId, noteDevoir); //TODO139 : Ajouter plutot ça au set de l'élève
Ce todo est pour un autre ticket ?

2022-09-07 10:02 UTC, BastienBenard commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +            }
```suggestion
            let promise: Promise<any>
            if (idMatiere != null) {
                promise = eleve.getMoyenne($scope.releveNote.devoirs.all, $scope.releveNote.idEtablissement, idClasse, $scope.releveNote.periode.id, idMatiere)
            }
            else {
                promise = eleve.getMoyenne($scope.releveNote.devoirs.all)
            }
            promise.then(() => {
                    if(!eleve.moyenneFinaleIsSet){
                        eleve.moyenneFinale = eleve.moyenne;
                        eleve.oldMoyenneFinale = eleve.moyenne;
                    }
                    $scope.calculerMoyenneClasse();
                    utils.safeApply($scope);
                });
```
Je ne sais pas si ce que je propose marche, a tester.

2022-09-07 10:17 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    Promise<Object> servicesPromise = Promise.promise();
Pourquoi est ce que tu ne type pas la promise ? Comme ça tu a pas besoin du cast  l 755

2022-09-07 10:21 UTC, BastienBenard commented on src/main/java/fr/openent/competences/bean/StatMat.java
> +                if(note.getString("id_eleve_moyenne_finale") != null && note.getValue("moyenne") != null && !note.getValue("moyenne").equals("-100")) {
il y a un cas ou la moyenne peut etre a -100 ?

2022-09-07 10:22 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +    //private ExportBulletinService exportBulletinService;
commentaire

2022-09-07 10:22 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        //exportBulletinService = new DefaultExportBulletinService(eb, null);
commentaire

2022-09-07 10:26 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                            //utilsService.addToMap(null, mNull.get(sousMatiereId), noteDevoir);
Est ce que c'est normale que l'on garde ce code commenté ?

2022-09-07 12:40 UTC, lapeyronnie requested changes

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> -                        decimalFormat.format(total / totalCoeff) : "NN";
String moyenne = hasNote ?
                        decimalFormat.format(total / totalCoeff) : "NN";

Pourquoi avoir supprimé cette partie ?  juste pour rappel une moyenne pour une matière, une période, une classe et un élève peut-être 'NN'. Dans ce cas, elle est sauvegardée en base dans la table moyenne_finale avec une valeur null.

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
Si je ne me trompe pas cette méthode ne permet pas de faire un arrondi en tenant compte du centième supérieur : 
1,85 -> 1,8 au lieu de 1,9 souhaité

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
>                                                  if(data.containsKey(MOYENNE)){
commentaire

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
>                      }
commentaire

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
>                                      List<NoteDevoir> notePeriode = entry.getValue();
le TODO a été oublié ? les moyennes finales ont été gérées ? J'ai l'impression que oui, un peu plus bas mais je n'en suis pas sûre merci de me confimer.

2022-09-07 12:40 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        query.append("SELECT notes.id_devoir, notes.id_eleve, notes.valeur, devoirs.coefficient, devoirs.diviseur, devoirs.ramener_sur, devoirs.owner, devoirs.id_matiere, devoirs.id_sousmatiere, grp.
pour facilité la relecture des PR, un retour à la ligne serait appréciable

2022-09-07 13:53 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                Double moyenne = Math.round((total / totalCoeff) * 10.0) / 10.0;
totalCoeff ne peut pas être NULL ou égale à zéro ?

2022-09-07 15:37 UTC, FlorentMr commented on src/main/java/fr/openent/competences/bean/StatMat.java
> +                if(note.getString("id_eleve_moyenne_finale") != null && note.getValue("moyenne") != null && !note.getValue("moyenne").equals("-100")) {
C'est du polymorphisme pris d'une autre fonction, donc ce check était déjà existant et je l'ai laissé au cas où un problème du genre serait déjà survenu

2022-09-07 16:00 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/Eleve.ts
> +                let idDevoirsURL:String = "";
N'utilise pas l'objet `String`, utilise `string `

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

2022-09-07 16:04 UTC, JinDouang commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +            }
Il peut faire direct en await

et faire sa verification directement

```suggestion
     if (idMatiere != null) {
                await eleve.getMoyenne($scope.releveNote.devoirs.all, $scope.releveNote.idEtablissement, idClasse, $scope.releveNote.periode.id, idMatiere);
            } else {
                await eleve.getMoyenne($scope.releveNote.devoirs.all);
            }
            if(!eleve.moyenneFinaleIsSet){
                eleve.moyenneFinale = eleve.moyenne;
                eleve.oldMoyenneFinale = eleve.moyenne;
            }
            $scope.calculerMoyenneClasse();
            utils.safeApply($scope);
```

j'ai pas mis de try catch car je sais pas ce qu'il se passe si ça fail ?

2022-09-09 13:17 UTC, FlorentMr commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> -                        decimalFormat.format(total / totalCoeff) : "NN";
Corrigé quelques lignes plus bas

2022-09-09 13:37 UTC, JinDouang requested changes

2022-09-09 13:37 UTC, JinDouang commented on src/main/java/fr/openent/competences/bean/StatEleve.java
> +import fr.openent.competences.service.impl.DefaultNoteService;
Ton import n'est pas utilisé

2022-09-09 13:37 UTC, JinDouang commented on src/main/java/fr/openent/competences/bean/StatEleve.java
> +            if (totalCoeff < 1) {
Vu avec @FlorentMr pour modifier la condition

2022-09-09 13:37 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    private static final double ROUNDER = 10.0;
Tu pourrais ajouter "10" et "20" dans ta classe Field ou une classe constante qui stockerait tes magic number!

2022-09-09 13:37 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                                                r.put(Field.MOYENNE,"NN");
Typiquement NN pourrait être dans ton Field ou ta nouvelle classe qui concerne énormément les coeff/values niveau chiffres

2022-09-09 13:37 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                                            Renders.renderJson(request, utilsService.calculMoyenne(notes, false, 20,false));
Si possible magic number 20 à traiter

2022-09-09 13:37 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/Eleve.ts
> +    getMoyenne (devoirs, idEtablissement, idClasse, idPeriode, idMatiere?) : Promise<any> {
Si possible, typer tes paramètres si tu les connais

2022-09-09 13:40 UTC, lapeyronnie approved these changes

2022-09-09 14:09 UTC, JinDouang approved these changes

2022-09-09 14:11 UTC, merged