Eval334/calcul max comp note item rwork
OPEN-ENT-NG/competences pull request #121
Opened 2022-09-15 07:59 UTC by Rseuret

## Describe your changes
La fonction max doit handle aussi le calcul moyen
## Checklist tests

## Issue ticket number and link

https://jira.support-ent.fr/browse/EVAL-332

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-15 13:05 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> -                compNote.put("evaluation", moyenneConverted).put("niveau_final", moyenneConverted);
Pourquoi avoir supprimé cette ligne, qui permet d'avoir la conversion de la moyenne dans l'échelle de convertion ?

2022-09-15 13:07 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +
commentaire

2022-09-15 13:24 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                    }
une matière peut évaluer plusieurs fois une competence, donc si j'ai bien suivi il manque un calcuk de moyennevensuite.

2022-09-15 13:25 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
>                  else
ici c'est la moyenne d'une compétence évaluée sur plusieurs matières

2022-09-16 12:16 UTC, JinDouang requested changes

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        Promise<Boolean> isAvgSkillpromise = Promise.promise() ;
Tu pourrais dans DefaultStructureOptions ajouter la méthode `isAverageSkills` qui reprendrait la méthode pour seulement retourner true comme on s'aperçoit qu'il est très souvent utilisé : 

DefaultStructureOptions : 
```
@Override
    public Future<Boolean> isAverageSkills(String structureId) {
        Promise<Boolean> promise = Promise.promise();
        getIsAverageSkills(structureId, event -> {
            if(event.isRight())
                promise.complete(event.right().getValue().getBoolean(Field.IS_AVERAGE_SKILLS)); // pour "is_average_skills"
            else
                promise.fail(event.left().getValue());
        });
        return promise.future();
    }
```

Et donc par la suite faire : 

```suggestion
        Future<Boolean> isAvgSkillpromise = structureOptionsService.isAverageSkills(idEtablissement);
                listFutures.add(isAvgSkillpromise);
```

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +
Tu pourrais dans DefaultStructureOptions ajouter la méthode `isAverageSkills` qui reprendrait la méthode pour seulement retourner true comme on s'aperçoit qu'il est très souvent utilisé : 

DefaultStructureOptions : 
```
@Override
    public Future<Boolean> isAverageSkills(String structureId) {
        Promise<Boolean> promise = Promise.promise();
        getIsAverageSkills(structureId, event -> {
            if(event.isRight())
                promise.complete(event.right().getValue().getBoolean(Field.IS_AVERAGE_SKILLS)); // pour "is_average_skills"
            else
                promise.fail(event.left().getValue());
        });
        return promise.future();
    }
```

Et donc par la suite faire : 

```suggestion
        Future<Boolean> isAvgSkillpromise = structureOptionsService.isAverageSkills(idEtablissement);
                listFutures.add(isAvgSkillpromise);
```

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                structureOptionsService.getIsAverageSkills(idEtablissement, event -> {
Voir commentaire en dessous pour une suggestion

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java
> +                    isAvgSkillpromise.complete(event.right().getValue().getBoolean("is_average_skills"));
Voir commentaire en dessous pour une suggestion

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        detailsFuture.add(isAvgSkillpromise.future());
Voir commentaire au dessus pour une suggestion

2022-09-16 12:16 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        isAvgSkillpromise.future()
Voir commentaire en dessous pour une suggestion (à réadapter sur l'appel seulement!)

```suggestion
            structureOptionsService.isAverageSkills(idEtablissement)
                        .onSuccess(isAverage -> {
                            ...
                        })
                        .onFailure(err -> {
                            ...
                        })
```

2022-09-19 13:38 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> -                compNote.put("evaluation", moyenneConverted).put("niveau_final", moyenneConverted);
non nécessaire et ne pose pas de problème pour le reste du code

2022-09-19 13:39 UTC, lapeyronnie commented on src/main/resources/public/ts/services/structureOptions.ts
> +
fichier supprimé

2022-09-19 13:39 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                    }
la moyenne est faite plus bas dans le code

2022-09-20 10:04 UTC, JinDouang approved these changes

2022-09-22 08:59 UTC, merged