eval-139 : final fixes
OPEN-ENT-NG/competences pull request #122
Opened 2022-09-16 10:04 UTC by FlorentMr

## Describe your changes
Fixes to diverse things, such as Appreciation Professeurs screen not being calculated, front average not being correctly calculated, some rebase problems, ...

## Checklist tests
At this point, all the screens will be tested alltogether to ensure everything is functionnal.

## Issue ticket number and link
Parent ticket : [EVAL-139](https://jira.support-ent.fr/browse/EVAL-139)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-16 12:54 UTC, BastienBenard commented on src/main/resources/public/template/pdf/releve-classe.pdf.xhtml
> +                    <span class="pretty center">{{libelle}}   <sup class="coeff">{{coeff}}</sup></span></div>
indentation

2022-09-16 12:54 UTC, BastienBenard commented on src/main/resources/public/template/pdf/releve-classe.pdf.xhtml
> +                    <span class="pretty center">{{libelle}}   <sup class="coeff">{{coeff}}</sup></span></div>
indentation

2022-09-16 12:55 UTC, BastienBenard commented on src/main/resources/public/ts/utils/functions/average.ts
> +function getSumAndCoeff (devoirs) {
typage retour

2022-09-19 06:20 UTC, JinDouang requested changes

2022-09-19 09:54 UTC, JinDouang approved these changes

2022-09-19 11:45 UTC, merged