feat(reportModel): #EVAL-174 rework report bulletin using now right and structureId
OPEN-ENT-NG/competences pull request #136
Opened 2022-10-13 14:12 UTC by simonchaval

## Describe your changes
Rework report bulletin using now right and strucutreId. Users with specifics rights can now see all report model bulletin from their structure.
## Checklist tests
Compétences -> Générer les bulletins -> bouton "Modèles de bulletin"
Vérifier :
- la récupération des modèles de bulletins (par établissement)
- la modification d'un titre de modèle de bulletin (seul le créateur du modèle peut le modifier)
- la suppression d'un  ou plusieurs modèle de bulletin (seul le créateur du modèle peut le supprimer)

## Issue ticket number and link
[EVAL-174](https://jira.support-ent.fr/browse/EVAL-174)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-14 08:22 UTC, lapeyronnie commented
la méthode getReportModelSelected doit être aussi mis à jour avec la récupératio ndu model selectionné par l'user et la structure choisie, non ?

2022-10-14 09:22 UTC, lapeyronnie requested changes

2022-10-18 13:16 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/model/ReportModelPrintExport.java
> +        return this.structureId;
getStructureId, pour ne pas confondre avec l'objet structure

2022-10-18 13:16 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/model/ReportModelPrintExport.java
> +        this.structureId = structure;
même remarque que pour le get

2022-10-18 13:16 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/security/UserIdStructure.java
> +}
Pourquoi avoir créer cette classe ? si je ne me trompe pas tu ne l'utilises pas

2022-10-18 13:16 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/security/modelbulletinrights/ModelExportBulletin.java
> +}
Pourquoi avoir créer cette classe ? si je ne me trompe pas tu ne l'utilise pas.

2022-10-24 12:45 UTC, simonchaval commented on src/main/java/fr/openent/competences/controllers/ReportModelPrintExportController.java
>      }
Oui, le structureId est présent dans le ReportModelPrintExport newReportModel grâce à la méthode createReportModelWithBodyRequest(bodyrequest).

2022-11-21 13:05 UTC, simonchaval commented on src/main/resources/public/ts/services/ReportModelPrintExportService.ts
> +    getAll: async (structureId):Promise<Array<ReportModelPrintExport>> => {
Dans les services en typescript, il y a un dossier "types". A cet endroit la méthode "getAll" est déclarée et typée.
Le paramètre "structureId" est donc typé en String à cet endroit.

2022-11-25 14:40 UTC, Rseuret approved these changes

2022-11-25 14:40 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/ReportModelPrintExportController.java
> +        String idReportModel = request.getParam("idReportModel");
magic String

2022-11-25 14:40 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/ReportModelPrintExportController.java
> +        String structureId = bodyRequest.getString("structureId");
magic String

2022-11-25 15:54 UTC, FlorentMr commented on src/main/java/fr/openent/competences/controllers/ReportModelPrintExportController.java
> +        String idStructure = request.getParam("structureId");
Magic String

2022-11-25 15:54 UTC, FlorentMr commented on src/main/java/fr/openent/competences/enums/report_model_print_export/ReportModelPrintExportMongo.java
> +    KEY_STRUCTUREID("structureId"),
Magic String?

2022-11-25 15:54 UTC, FlorentMr commented on src/main/java/fr/openent/competences/security/modelbulletinrights/UserIdModelExportBulletin.java
> +        String idReportModel = request.getParam("idReportModel");
Magic String

2022-11-28 11:37 UTC, lapeyronnie approved these changes

2022-11-28 11:40 UTC, merged