feat(exercizer) : #EVAL-397 Import, edit and parse Exercizer-based CSV.
OPEN-ENT-NG/competences pull request #137
Opened 2022-10-20 14:09 UTC by FlorentMr

## Describe your changes
Import, edit and parse Exercizer-based CSV to use them later on for an evaluation set or update.

## Checklist tests
can test API /notes/:id/:typeImportService/csv, but can wait for the whole #EVAL-45 to be done for the testing.

## Issue ticket number and link
[EVAL-397](https://jira.support-ent.fr/browse/EVAL-397)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-21 08:54 UTC, sjollois requested changes

2022-10-21 08:54 UTC, sjollois commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    // renderJson
il manque des choses dedans ?

2022-10-21 08:54 UTC, sjollois commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    // renderError
idem

2022-10-21 08:54 UTC, sjollois commented on src/main/java/fr/openent/competences/importservice/ImportFile.java
> +    public Future<Buffer> processImportFile() {
Je te conseille d'utiliser les librairie vertx pour écrire et lire un fichier temporaire. Et ce en mode stream (ligne par ligne).
Bastien a fait cela dans la PR de CRRE : https://github.com/CGI-OPEN-ENT-NG/crre/pull/26

2022-10-21 08:54 UTC, sjollois commented on src/main/java/fr/openent/competences/helpers/FileHelper.java
> +                    String message = "[PresenceCommon@FileHelper::removeFiles] Failed to remove files.";
C'est plus PresenceCommon :p

2022-10-21 13:14 UTC, FlorentMr commented on src/main/java/fr/openent/competences/helpers/FileHelper.java
> +                    String message = "[PresenceCommon@FileHelper::removeFiles] Failed to remove files.";
Oups bien vu

2022-10-21 13:14 UTC, FlorentMr commented on src/main/java/fr/openent/competences/importservice/ImportFile.java
> +    public Future<Buffer> processImportFile() {
C'est ce qu'on a utilisé avec Jin, et utiliser vertx maintenant demanderait pas mal de temps en plus pour un résultat similaire, j'aimerais autant éviter de repasser à ce point sur le code, mais si c'est une meilleure pratique je garde ça de côté pour utiliser ça à la prochaine occasion (ou réécrire le Helper plus tard)

2022-10-21 13:14 UTC, FlorentMr commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    // renderError
idem que plus haut

2022-10-21 13:14 UTC, FlorentMr commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    // renderJson
Oui j'aurais du plus préciser, mais ça sera de la gestion de retour qui sera fait dans un prochain ticket

2022-10-25 07:48 UTC, lapeyronnie approved these changes

2022-10-25 07:50 UTC, merged