feat(exercizer) : EVAL-398 Now insert or update notes depending on an Exercizer-type CSV.
OPEN-ENT-NG/competences pull request #138
Opened 2022-10-25 09:14 UTC by FlorentMr

## Describe your changes
Added the possibility to insert or update notes depending while importing an Exercizer-type CSV.

## Checklist tests
API testing /notes/:id/:typeImportService/csv/:classId/:devoirId, else wait for the front ticket.

## Issue ticket number and link
[EVAL-398](https://jira.support-ent.fr/browse/EVAL-398)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-25 09:58 UTC, sjollois requested changes

2022-10-25 11:49 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +        AtomicReference<Boolean> hasStudentConflict = new AtomicReference<>(true);
Il ne sert pas cette atomic si ?

2022-10-25 11:50 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                    return promise.future();
return exercizerImportNote.sql(idClasse, idDevoir, res)

2022-10-25 11:50 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                            .put("status", res)
magic string

2022-10-25 12:00 UTC, BastienBenard commented on src/main/java/fr/openent/competences/importservice/ImportFile.java
> +    public abstract Future<Boolean> sql(String idClasse, String idDevoir, List<ExercizerStudent> students);
Java doc.
Je ne suis pas sur que le nom de la méthode sois très parlant.

2022-10-25 12:04 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/NoteService.java
> +    void insertOrUpdateDevoirNote (String idDevoir, String idEleve,  Double valeur, Handler<Either<String, JsonObject>> handler);
Java doc

2022-10-25 12:05 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        JsonArray values = new fr.wseduc.webutils.collections.JsonArray();
fr.wseduc.webutils.collections.JsonArray => JsonArray

2022-10-25 12:11 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +    public void getClasseDisplaynames(String idClasse, Handler<Either<String, JsonArray>> result){
Tu peux peut etre utiliser l'event bus de vie scolaire https://github.com/OPEN-ENT-NG/vie-scolaire/blob/17c58ec35a6bf9beda97dead58d1e9c22f405411/src/main/java/fr/openent/viescolaire/controller/EventBusController.java#L434

2022-10-26 08:02 UTC, FlorentMr commented on src/main/java/fr/openent/competences/importservice/ExercizerImportNote.java
> +                    return Future.succeededFuture(hasStudentConflict);
En tout cas sur les tests que j'ai fait j'ai eu aucun soucis, pourquoi? Un potentiel problème de synchronisation pourrait survenir avec mon code? Ya une pratique que j'ai oublié?

2022-10-26 12:27 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/helpers/FutureHelper.java
>          return event -> {
attention cette méthode (handlerJsonObject) utilisée : cela pourrait avoir des impacts de la redéfinir

2022-10-26 12:41 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +    public void getClasseDisplaynames(String idClasse, Handler<Either<String, JsonArray>> result){
Dans compétences, il y a déjà cette méthode dans compétence classe Utils. Par contre, on avait oublié mais on va avoir besoin aussi de la période

2022-10-26 12:44 UTC, FlorentMr commented on src/main/java/fr/openent/competences/helpers/FutureHelper.java
>          return event -> {
Je n'ai pas vu d'autres utilisations que la mienne dans le code, je n'ai pas l'impression que ce changement puisse avoir un impact

2022-10-26 13:13 UTC, FlorentMr commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +    public void getClasseDisplaynames(String idClasse, Handler<Either<String, JsonArray>> result){
On va gérer l'id période et le type classe plus tard finalement (discuté avec Agnes)

2022-10-26 13:59 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    @Post("/notes/:id/:typeImportService/csv/:classId/:devoirId")
Si tu change la route il faut que tu met la doc d'API dans la description de ta PR.
Si tu veux respecter le nomage des route d'API Rest je te conseille 
"/notes/:id/class/:classId/devoir/:devoirId/type/:typeImportService/csv"

Je crois que typeImportService n'est pas utiliser, on le grade quand même dans la route ?

C'est une API pas encore utilisé ? Est ce que il va avoir un future ticket pour modifier les appels du front ?

2022-10-26 13:59 UTC, BastienBenard commented on src/main/java/fr/openent/competences/importservice/ImportFile.java
> +
Pourquoi rajouter ces import ?

2022-10-26 13:59 UTC, BastienBenard commented on src/main/java/fr/openent/competences/importservice/ExercizerImportNote.java
> +                            noteService.insertOrUpdateDevoirNote(idDevoir, j.getString("id"), student.getNote(), FutureHelper.handlerJsonObject(insertOrUpdatePromise));
magic String

2022-11-04 15:53 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                                renderError(request);
des logs errors plus tôt, non ?

2022-11-08 15:13 UTC, merged