EVAL-399: import notes with the exercozer csv file part front
OPEN-ENT-NG/competences pull request #139
Opened 2022-10-26 09:53 UTC by lapeyronnie

## Describe your changes
ajout d'un bouton et une popup pour import un fichier csv
[EVAL-45](https://jira.support-ent.fr/browse/EVAL-45)
## Checklist tests

## Issue ticket number and link
[EVAL-399](https://jira.support-ent.fr/browse/EVAL-399)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-10-26 10:26 UTC, qpic-cgi requested changes

2022-10-26 10:26 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +            //onImport: "&",
supprime ce commentaire

2022-10-26 10:26 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +                private $location:ILocationService,
tu n'as pas l'air de te servir de ton location, tu peux faire du nettoyage du coup 😄

2022-10-26 12:36 UTC, sjollois requested changes

2022-10-26 12:36 UTC, sjollois commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +            await NoteService.importNote(this.devoir.id_groupe, this.devoir.id)
tu ne mets pas ton formData dedans ?

2022-10-26 12:53 UTC, lapeyronnie commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +                private $location:ILocationService,
pour l'instant

2022-10-26 13:04 UTC, lapeyronnie commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +            await NoteService.importNote(this.devoir.id_groupe, this.devoir.id)
bien vu

2022-10-26 13:06 UTC, qpic-cgi approved these changes

2022-11-03 13:58 UTC, sjollois approved these changes

2022-11-08 15:42 UTC, merged