feat(exercizer) : EVAL-45 Fixed some inconsistencies between front and back.
OPEN-ENT-NG/competences pull request #144
Opened 2022-11-14 10:33 UTC by FlorentMr

## Describe your changes
Fixed some inconsistencies between front and back, such as the URL used and some variables.

## Checklist tests

## Issue ticket number and link
[EVAL-45](https://jira.support-ent.fr/browse/EVAL-45)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-14 11:03 UTC, sjollois approved these changes

2022-11-14 11:04 UTC, sjollois commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
> +                            this.$window.location.reload(true);
Tu es obligé de reload la page ? ce n'est pas ouf en terme d'UX

2022-11-14 14:41 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    @Post("/notes/:typeImportService/csv/exercizer/import/:classId/:devoirId/:classType/:periodeId")
Tu n'as pas mis la doc d'API dans ta description

2022-11-14 14:43 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    @Post("/notes/:typeImportService/csv/exercizer/import/:classId/:devoirId/:classType/:periodeId")
A voir avec ton Tech mais il commence a avoir pas mal de parm dans l'URL ce serait peut être mieux de les passer dans le body

2022-11-14 14:48 UTC, BastienBenard commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
>                  .then((response: AxiosResponse) => {
Je vois qu'il y a pas de catch, est ce que tu peux en rajouter un basic (console.error)

2022-11-14 14:51 UTC, BastienBenard commented on src/main/resources/public/ts/services/note.service.ts
> +    importNote(classId: string, devoirId: number, classType: number, periodeId: number | string, formData: FormData): Promise<AxiosResponse>;
periodeId c'est un UUDI ou un entier ? Si possible ce serais bien d'éviter les multiples typage en TS

2022-11-14 15:35 UTC, JinDouang requested changes

2022-11-14 15:35 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    @Post("/notes/:typeImportService/csv/exercizer/import/:classId/:devoirId/:classType/:periodeId")
Pas nécessaire, il faudrait limite plus préciser les endpoints même si c'est long : 

`/notes/:typeImportService/csv/exercizer/import/classes/:classId/devoirs/:devoirId/:classType/periods/:periodeId`

2022-11-14 15:35 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                promise.complete();
Si tu décides de ne rien compléter dans ta promise, dans ce cas il faudrait lui passer `Promise<Void>` dans ta méthode

2022-11-14 15:35 UTC, JinDouang commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
>                  .then((response: AxiosResponse) => {
A voir si un flow est prévu en cas d'erreur (si le catch est nécessaire ou pas)

2022-11-15 09:14 UTC, lapeyronnie commented on src/main/resources/public/ts/directives/import-note/import-note.directive.ts
>                  .then((response: AxiosResponse) => {
Gérer là où le service est utilisé

2022-11-15 10:59 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +    @Post("/notes/:typeImportService/csv/exercizer/import/:classId/:devoirId/:classType/:periodeId")
Yes, le Post est intéressant quand tu veux passer des listes (d'identifiants la plus part du temps) en paramètre.

2022-11-15 11:02 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +                        });
suggest: 
```suggestion
List<Future<JsonObject>> futures = students.stream().filter(student -> isNotNull(student.id()))
.map(student -> notesService.insertOrUpdateDevoirNote(idDevoir, student.id(), student.getNote()))
.collect(Collectors.toList())
```

2022-11-15 11:04 UTC, qpic-cgi approved these changes

2022-11-15 12:17 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/NoteController.java
> +        final String idPeriode = request.params().get(Field.PERIODEID);
Je vois que l'idPeriode est un Long. Tu devrais plutôt caster en Long ici puis faire descendre ton paramètre (de type Long et non String mtn), plutot que l'inverse. ça te permettra de géré l'exception et de renvoyer un Bad request.

2022-11-15 12:18 UTC, BastienBenard commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +        studentAvailableForPeriode(idClasse, Long.valueOf(idPeriode), Integer.valueOf(typeClasse), message -> {
https://github.com/OPEN-ENT-NG/competences/pull/144/files#r1022718102
Ici tu ne fais aucun vérif si ton idPeriode est bien un Long

2022-11-22 13:40 UTC, Rseuret approved these changes

2022-11-22 13:40 UTC, Rseuret commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +            console.log("methodLoadNote");
le console.log est encore utile?

2022-11-25 15:15 UTC, merged