fix(ExportPDF) : #EVAL-436 Fixes some subjects not taking in account subtopic coeffs PDF export when the marks were on a multi-class group.
OPEN-ENT-NG/competences pull request #154
Opened 2022-12-21 11:26 UTC by FlorentMr

## Describe your changes
Fixes some subjects not taking in account subtopic coeffs PDF export when the marks were on a multi-class group.

## Checklist tests
Suivi Classe -> Moyennes tab -> Check if the pdf has the same averages as in Releve Periodique

## Issue ticket number and link
[EVAL-436](https://jira.support-ent.fr/browse/EVAL-436)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-12-21 15:02 UTC, BastienBenard approved these changes
Si tu a le temps, ce serait cool de faire des tests sur DefaultSubTopicService.java et DefaultUtilsService.java

2022-12-22 08:43 UTC, sjollois approved these changes

2023-01-03 15:26 UTC, JinDouang requested changes

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/SubTopicService.java
> +    void getSubtopicServices(String idStructure, JsonArray idsClasse, Handler<Either<String, JsonArray>> handler);
Possibilité de faire en future ?

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/UtilsService.java
> +    void getSubTopicCoeff(String idEtablissement, JsonArray idsClasse, Promise<List<SubTopic>> promise);
Possibilité de faire en future ?

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +        Sql.getInstance().prepared(query,params,validResultHandler(handler));
Possibilité de faire une future avec le model `SubTopic ` ?

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +    public void getSubTopicCoeff(String idEtablissement, JsonArray idsClasse, Promise<List<SubTopic>> promise) {
Possibilité de faire une future ?

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +                setSubtopics(promise, event);
Cette méthode `setSubtopics `pourrait être polymorphé en faisant en sorte que `setSubtopics ` soit une Future

2023-01-03 15:26 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +        Sql.getInstance().prepared(query,params,validResultHandler(handler));
```suggestion
  Sql.getInstance().prepared(query,params,validResultHandler(event -> {
                        if (event.isRight()) {
                            promise.complete(event.right().getValue())
                        } else {
                            log.error(String.format("[DefaultUtilsService@%s::getSubTopicCoeff] Error during request : %s.",
                                    this.getClass().getSimpleName(), event.left().getValue()));
                            promise.fail(event.left().getValue())
                        }
   }));
```

2023-01-09 15:23 UTC, JinDouang requested changes

2023-01-09 15:23 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultSubTopicService.java
> +    private Future<JsonArray> getJsonArrayFuture(Promise<JsonArray> promise, String query, JsonArray params) {
Pas en paramètre la promise!

2023-01-09 17:02 UTC, merged