fix(security): EVAL-441 Securise routes for CompetenceNoteController, DigitalSkillsController, ElementBilanPeriodiqueController and ExportBulletinController with ressource filter
OPEN-ENT-NG/competences pull request #165
Opened 2023-01-16 10:00 UTC by Alex-Delaveau

## Describe your changes
Securise API routes with ressources filters and unit tests.
## Checklist tests

## Issue ticket number and link
[EVAL-441](https://jira.support-ent.fr/browse/EVAL-441)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-16 13:47 UTC, lapeyronnie requested changes

2023-01-16 13:47 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/security/AccessStructureAndAdminOrTeacherCourseFilter.java
> +                isTeacherWhomClassBelong = user.getClasses().contains(request.params().get(Field.IDCLASSE));
/!\ idClass peut-être aussi un groupe => à vérifer aussi

2023-01-17 13:08 UTC, lapeyronnie approved these changes

2023-01-17 14:38 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/BilanPeriodique.ts
> +    async syncAppreciations (elements, periode, classe, structure) {
typage de structure

2023-01-17 14:42 UTC, JinDouang requested changes

2023-01-17 14:42 UTC, JinDouang commented on src/main/resources/public/ts/models/teacher/BilanPeriodique.ts
> +            let url = BilanPeriodique.api.GET_APPRECIATIONS + '?idPeriode=' + periode.id + '&idClasse=' + classe.id +
typage url en string du coup

2023-01-17 14:42 UTC, JinDouang commented on src/main/java/fr/openent/competences/security/AccessStructureAndAdminOrTeacherCourseFilter.java
> +        if(request.params().contains(Field.IDCLASSE) && request.params().contains(Field.IDENSEIGNANT)){
Pas possible de mettre ton if "child" au même niveau que tes autres ifs ?

2023-01-17 15:01 UTC, Alex-Delaveau commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
Delete Get("/competences/note") API route in CompetencesNoteController because it is not used anywhere in frontend.

2023-01-17 15:01 UTC, Alex-Delaveau commented on src/main/java/fr/openent/competences/controllers/CompetenceNoteController.java
> -    }
Delete Get("/competences/note") API route in CompetencesNoteController because it is not used anywhere in frontend.

2023-01-17 15:57 UTC, JinDouang approved these changes

2023-01-17 16:11 UTC, merged