fix(ReleveNote) : EVAL-454 Fixes multiclasses group not taking in account their subtopics coefficients on PDF of Suivi Eleve.
OPEN-ENT-NG/competences pull request #166
Opened 2023-01-16 13:19 UTC by FlorentMr

## Describe your changes
Fixes multiclasses group not taking in account their subtopics coefficients on PDF of Suivi Eleve.

## Checklist tests
Suivi Eleve-> Suivi des Notes tab -> Check if the PDF has the right subjects and averages.

## Issue ticket number and link
[EVAL-454](https://jira.support-ent.fr/browse/EVAL-454)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-16 13:46 UTC, lapeyronnie requested changes

2023-01-16 13:46 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +
ce n'est pas la méthode getAllMultiTeacher plutôt ? pour pouvoir récupérer les remplaçants ou coenseignant d'un groupe

2023-01-16 13:46 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                        devoirsJSON.add(annotationJson);
magic string

2023-01-16 13:46 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    }
magic string

2023-01-16 14:05 UTC, lapeyronnie commented
erreur en front :  let classe = _.findWhere(classAndGroups, {id_classe : $scope.search.classe.id});
            let subTopicsServices = subTopicsServicesStruct.filter(subTopic =>
                subTopic.id_group === $scope.search.classe.id || _.contains(classe.id_groupes, subTopic.id_group)
            );

class est undefined lorsque l'on est dans le cas d'un group

2023-01-17 09:35 UTC, Rseuret requested changes

2023-01-17 09:35 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    annotationsJSON.stream().forEach(annotation -> {
cela prendrait du temps de modéliser les données plutôt que de passer par un json?

2023-01-17 09:35 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    final JsonObject etabJSON = structureFuture.result().getJsonObject("s").getJsonObject("data");
magic String

2023-01-17 09:35 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    if (null != params.get("idTypePeriode") && null != params.get("ordrePeriode")) {
magic String
(1860 - 1867)

2023-01-17 09:35 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                            idEnseignants.add(service.getString("id_enseignant"));
magic string

2023-01-17 09:35 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                            idEnseignants.add(multiTeacher.getString("second_teacher_id"));
magic string

2023-01-17 10:18 UTC, FlorentMr commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +
getMultiTeachers permet déjà de récupérer les remplaçants/coenseignants d'un groupe tant que son id est présent dans idGroupClasse (ce qui est le cas avec l'ajout de getGroupesClasse plus haut)

2023-01-17 10:19 UTC, FlorentMr commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    annotationsJSON.stream().forEach(annotation -> {
Ce n'est pas une partie de code que j'ai écrit moi même, j'ai simplement rajouté la méthode getGroupesClasse plus haut, git donne l'impression que j'ai écrit ça mais ce n'est pas le cas, donc je préfère laisser la gestion des données comme tel

2023-01-17 14:19 UTC, Rseuret approved these changes

2023-01-17 14:41 UTC, lapeyronnie approved these changes

2023-01-17 14:52 UTC, merged