fix(security): #EVAL-456 security on ExportPDFController
OPEN-ENT-NG/competences pull request #170
Opened 2023-01-23 14:46 UTC by Gregprod33

## Describe your changes
Security checks for ExportPDFController's routes.
## Checklist tests
Unit tests and Postman
## Issue ticket number and link
[#EVAL-456](https://jira.support-ent.fr/browse/EVAL-456)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-23 16:02 UTC, sjollois approved these changes

2023-01-24 08:15 UTC, lapeyronnie requested changes

2023-01-24 08:15 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/security/AccessSuiviClasse.java
> +        }
attention ne pas utiliser le filtre sur la classe ou seulement pour le profil Teacher car le droit d'accès au conseil de classe est donné à des utilisateur qui n'ont pas de classes.

2023-01-24 14:30 UTC, lapeyronnie approved these changes

2023-01-26 11:01 UTC, lapeyronnie approved these changes

2023-01-27 10:34 UTC, merged