fix(security): #EVAL-457 security on MatiereController
OPEN-ENT-NG/competences pull request #171
Opened 2023-01-24 09:11 UTC by Gregprod33

## Describe your changes
Security checks for MatiereController's routes
## Checklist tests

## Issue ticket number and link
[#EVAL-457](https://jira.support-ent.fr/browse/EVAL-457)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-24 09:56 UTC, qpic-cgi approved these changes

2023-01-24 10:00 UTC, sjollois approved these changes

2023-01-24 10:02 UTC, c4role approved these changes

2023-01-24 13:16 UTC, BastienBenard commented on src/main/java/fr/openent/competences/security/AccessIfMyStructure.java
> +                handler.handle(new FilterUserUtils(userInfos,null).validateStructure(structureId));
C'est dommage d'instancier un utils. Peut être crée une méthode statics dans le utils et passer les méthode d'instance en déprécier.

2023-01-24 13:16 UTC, BastienBenard commented on src/test/java/fr/openent/competences/security/AccessIfMyStructureTest.java
> +    UserInfos user = new UserInfos();
```suggestion
    UserInfos user;
```
Tu fais déjà l'instanciation dans le setup

2023-01-24 13:16 UTC, BastienBenard commented on src/test/java/fr/openent/competences/security/AdministratorRightTest.java
> +    UserInfos user = new UserInfos();
```suggestion
    UserInfos user;
```

2023-01-24 13:56 UTC, lapeyronnie approved these changes

2023-01-24 16:38 UTC, lapeyronnie requested changes

2023-01-24 16:38 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/security/AdministratorRight.java
> +        }
ce n'est pas cela que l'on avait convenu, il me semble : AdministratorRight  = appartenir à la structure et allowViesco && allowCompetences

2023-01-25 08:26 UTC, Gregprod33 commented on src/main/java/fr/openent/competences/security/AdministratorRight.java
> +        }
effectivement j'avais oublié la condition

2023-01-26 10:23 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/MatiereController.java
>      public void getModels(final HttpServerRequest request) {
Je n'avais pas vu mais cette route est aussi utilisé pour l'export des bulletins => ici il faut appartenir à la structure et avoir le droit exportBulletin

2023-01-27 09:45 UTC, lapeyronnie approved these changes

2023-01-27 11:18 UTC, merged