fix(security): #EVAL-458 security on NiveauDeMaitriseController
OPEN-ENT-NG/competences pull request #173
Opened 2023-01-24 16:36 UTC by Gregprod33

## Describe your changes
Handle route's security on NiveauDeMaitriseController
## Checklist tests

## Issue ticket number and link
[#EVAL-458](https://jira.support-ent.fr/browse/EVAL-458)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-24 16:42 UTC, BastienBenard approved these changes

2023-01-25 07:13 UTC, sjollois approved these changes

2023-01-25 09:16 UTC, qpic-cgi approved these changes

2023-01-25 17:30 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/NiveauDeMaitriseController.java
>      public void deleteUserFromPerso(final HttpServerRequest request){
Pour le post et le delete de /maitrise/perso/use erreur de ma part, il faut regarder si l'utilisateur connecté est bien le même que l'idUser envoyé

2023-01-25 17:31 UTC, lapeyronnie requested changes
deux modifications

2023-01-27 09:28 UTC, lapeyronnie approved these changes

2023-01-27 13:24 UTC, merged