fix(security): #EVAL-460 security on BFCController
OPEN-ENT-NG/competences pull request #174
Opened 2023-01-26 15:44 UTC by Gregprod33

## Describe your changes
Changing resourceFilter on some routes.
## Checklist tests
Testing routes ad variables with breakpoints in browser, 
## Issue ticket number and link
[#EVAL-460](https://jira.support-ent.fr/browse/EVAL-460)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-26 16:37 UTC, sjollois requested changes

2023-01-26 16:37 UTC, sjollois commented on src/main/java/fr/openent/competences/controllers/BFCController.java
> -    @Get("/delete/archive/bfc")
c'est voulu?

2023-01-26 16:37 UTC, sjollois commented on src/main/java/fr/openent/competences/controllers/BFCController.java
> +    @ResourceFilter(HasExportLSURight.class)
c'est pas le SuperAdmin ?

2023-01-27 09:18 UTC, Gregprod33 commented on src/main/java/fr/openent/competences/controllers/BFCController.java
> -    @Get("/delete/archive/bfc")
oui, sur le fichier confluence sécurité

2023-01-27 10:23 UTC, lapeyronnie approved these changes

2023-01-27 13:37 UTC, merged