refactor() : EVAL-462 use Promise and Future
OPEN-ENT-NG/competences pull request #177
Opened 2023-01-31 15:12 UTC by lapeyronnie

## Describe your changes
refacto code : methods use Promises and return Future 
## Checklist tests
vue du relevé périodique et export pdf et csv de ce relevé, pour toutes les périodes
## Issue ticket number and link  
[EVAL-462](https://jira.support-ent.fr/browse/EVAL-462)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-01 00:34 UTC, JinDouang requested changes

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultAppreciationService.java
> +    public Future<JsonArray> getAppreciationClasse(String[] id_classes, Integer id_periode, String[] id_matieres) {
En relisant ton code hors PR, je m'aperçois que tu polymorphes la méthode `public void getAppreciationClasse(String[] id_classes, Integer id_periode, String[] id_matieres, Handler<Either<String, JsonArray>> handler)`  en dupliquant ton code (https://github.com/OPEN-ENT-NG/competences/blob/32f73431716977fd74e56afcc8ed74fc411bc7ab/src/main/java/fr/openent/competences/service/impl/DefaultAppreciationService.java#L101)

Au lieu de réécrire le code, tu peux faire ta méthode qui appelle ta méthode (polymorphisme) de cette façon : 

```
  public Future<JsonArray> getAppreciationClasse(String[] id_classes, Integer id_periode, String[] id_matieres) {
        Promise<JsonArray> classAppreciationPromise = Promise.promise();
        // dans ton cas, tu appelles/utilises la méthode déjà existante mais tu l'adaptes de sorte à ce que cela te renvoie 
        // une future!
        getAppreciationClasse(id_classes, id_periode, id_matieres, event -> {
            if (event.isLeft()) {
                // instancier une classe logger dans cette classe pour ajouter log.error ?
                // private final Logger log = LoggerFactory.getLogger(DefaultAppreciationService.class);
                log.error(String.format("[Competences@%s::getAppreciationClasse] Error during sql request: %s.",
                        this.getClass().getSimpleName(), event.left().getValue()));
                classAppreciationPromise.fail(event.left().getValue());
            } else {
                classAppreciationPromise.complete(event.right().getValue());
            }
        });
        return classAppreciationPromise.future();
    }
```

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultCompetenceNoteService.java
> +    }
Même principe par rapport à mon commentaire au-dessus : utilise la méthode déjà existante pour polymorpher ta méthode que tu veux faire retourner une future 

Exemple usage : 

```suggestion
 public Future<JsonArray> getConversionNoteCompetence(String idEtablissement, String idClasse) {
        Promise<JsonArray> conversionTable = Promise.promise();
        getConversionNoteCompetence(idEtablissement, idClasse, event -> {
            if (event.isLeft()) {
                log.error(String.format("[Competences@%s::getConversionNoteCompetence] Error during sql request: %s.",
                        this.getClass().getSimpleName(), event.left().getValue()));
                conversionTable.fail(event.left().getValue());
            } else {
                conversionTable.complete(event.right().getValue());
            }
        });
        return conversionTable.future();
    }
```

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultElementProgramme.java
> +    }
Même principe par rapport à mon commentaire au-dessus : utilise la méthode déjà existante pour polymorpher ta méthode `getElementProgramme` que tu veux faire retourner une future

Exemple usage :

```suggestion
     public Future<JsonObject> getElementProgramme(Long idPeriode, String idMatiere, String idClasse){
        Promise<JsonObject> promiseElementProgramme = Promise.promise();
        getElementProgramme(idPeriode, idMatiere, idClasse, event -> {
            if (event.isLeft()) {
                // instancier une classe logger dans cette classe pour ajouter log.error ?
                // private final Logger log = LoggerFactory.getLogger(DefaultElementProgramme.class);
                log.error(String.format("[Competences@%s::getElementProgramme] Error during sql request: %s.",
                        this.getClass().getSimpleName(), event.left().getValue()));
                promiseElementProgramme.fail(event.left().getValue());
            } else {
                promiseElementProgramme.complete(event.right().getValue());
            }
        });

        return promiseElementProgramme.future();
    }
```

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultMatiereService.java
> +    }
Même principe par rapport à mon commentaire au-dessus : utilise la méthode déjà existante pour polymorpher ta méthode `getUnderSubjects` que tu veux faire retourner une future

Exemple usage :

```suggestion
   public Future<JsonArray> getUnderSubjects(String idMatiere, String idStructure) {
        Promise<JsonArray> underSubjectPromise = Promise.promise();
        getSousMatieres(idMatiere, idStructure, event -> {
            if (event.isLeft()) {
                log.error(String.format("[Competences@%s::getUnderSubjects] Error during sql request: %s.",
                        this.getClass().getSimpleName(), event.left().getValue()));
                underSubjectPromise.fail(event.left().getValue());
            } else {
                underSubjectPromise.complete(event.right().getValue());
            }
        });

        return underSubjectPromise.future();
    }
```

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                //Promise<Object> multiTeachingPromise = Promise.promise();
Commentaire voulu ?

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                      //  new JsonArray().add(idClasse), (idPeriode != null ? idPeriode.intValue() : null), FutureHelper.handlerJsonArray(multiTeachingPromise));
Commentaire voulu ?

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +    }
Même principe par rapport à mes commentaires au niveau du polymorphisme : utilise la méthode déjà existante pour polymorpher ta méthode `getStudentClassForExportReleve `que tu veux faire retourner une future.

Cette méthode est particulière puisque son dernier paramètre est une future qu'on passe en référence
Il faudrait (à voir si on peut mieux faire) déclarer une promise qui s'occupera de régler la méthode et de vérifier sa future pour retourner le résultat

Exemple usage :

```suggestion
 private Future<JsonArray> getStudentClassForExportReleve(String idClasse, Long idPeriode, JsonArray idEleves, Integer typeClasse,
                                                Map<String, JsonObject> eleveMapObject){
        Promise<JsonArray> promiseStudents = Promise.promise();

        Promise<JsonArray> studentClassFuture = Promise.promise();
        getStudentClassForExportReleve(idClasse, idPeriode, idEleves, typeClasse, eleveMapObject, studentClassFuture.future());
        studentClassFuture.future()
                .onSuccess(promiseStudents::complete)
                .onFailure(err -> {
                    log.error(String.format("[Competences@%s::getStudentClassForExportReleve] Error during request eb: %s.",
                            this.getClass().getSimpleName(), err.getMessage()));
                    promiseStudents.fail(err.getMessage());
                });
        return promiseStudents.future();
    }
```

2023-02-01 00:34 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultUtilsService.java
> +
Même principe par rapport à mon commentaire au-dessus : utilise la méthode déjà existante pour polymorpher ta méthode `getAllMultiTeachers ` que tu veux faire retourner une future

Exemple : 

```suggestion
public Future<JsonArray> getAllMultiTeachers(final String structureId, final JsonArray groupIds){
        Promise<JsonArray> promiseMultiTeachers = Promise.promise();
        getAllMultiTeachers(structureId, groupIds, event -> {
            if (event.isLeft()) {
                log.error(String.format("[Competences@%s::getAllMultiTeachers] Error during sql request: %s.",
                        this.getClass().getSimpleName(), event.left().getValue()));
                promiseMultiTeachers.fail(event.left().getValue());
            } else {
                promiseMultiTeachers.complete(event.right().getValue());
            }
        });
        return promiseMultiTeachers.future();
    }
```

2023-02-01 14:01 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +        Future<JsonObject> elementProgrammeFuture =
Perso, je préfère les ajouter au fur et à mesure pour ne pas les oublier

2023-02-01 14:02 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                //Promise<Object> multiTeachingPromise = Promise.promise();
ils seront supprimés dans le prochain ticket

2023-02-01 14:02 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultNoteService.java
> +                      //  new JsonArray().add(idClasse), (idPeriode != null ? idPeriode.intValue() : null), FutureHelper.handlerJsonArray(multiTeachingPromise));
ils seront supprimés dans le prochain ticket

2023-02-02 07:35 UTC, JinDouang approved these changes

2023-02-03 08:20 UTC, merged