fix(security): #EVAL-481 added right resource filter on api for security
OPEN-ENT-NG/competences pull request #193
Opened 2023-03-01 07:29 UTC by simonchaval

## Describe your changes
Added parameter in front end to match with security added in back end on one route of this controller.
Security file in back end already exist and ressource filter is applied.
## Checklist tests

## Issue ticket number and link
[EVAL-481](https://jira.support-ent.fr/browse/EVAL-481)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-01 15:23 UTC, Rseuret approved these changes

2023-03-02 09:24 UTC, FlorentMr approved these changes

2023-03-02 10:11 UTC, lapeyronnie approved these changes

2023-03-02 21:45 UTC, JinDouang requested changes

2023-03-02 21:45 UTC, JinDouang commented on src/main/java/fr/openent/competences/controllers/DigitalSkillsController.java
> +import javax.annotation.Resource;
Tu n'as pas l'air de l'utiliser tu peux enlever cet import je pense

2023-03-02 21:46 UTC, JinDouang reviewed
Je serai pas là mais essaye de traiter mon retour!

2023-03-15 17:41 UTC, merged