feat(ExportClasse) : #EVAL-228 Adds the possibility to print skills results to Releve de notes in Suivi Class.
OPEN-ENT-NG/competences pull request #207
Opened 2023-03-13 15:19 UTC by FlorentMr

## Describe your changes
Adds the possibility to print skills results to Releve de notes in Suivi Class via a list letting you chose between skills, scores and both skills&scores.

## Checklist tests
Suivi classe -> Download button -> "Le relevé de notes des élèves de la classe" -> test "Notes" and "Notes et compétences"

## Issue ticket number and link
[EVAL-228](https://jira.support-ent.fr/browse/EVAL-228)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-14 09:54 UTC, qpic-cgi requested changes

2023-03-14 09:54 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                                                        Map<String, Map<String, Long>> competenceNotesByDevoir) {
dans l'ordre des fonction,
on préfère

```java
public truc() {
    privMethod();
}

private privMethod() {
}
```

plutôt que:
```java
private privMethod() {
}

public truc() {
    privMethod();
}
```

2023-03-14 09:54 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +    }
Plutôt longue cette fonction.
essaie de découper en sous méthodes (une manière simple de le faire: chaque fois que tu fais un for, ou une boucle, pose toi la question de ce qu'elle fait => et là tu as le nom de ta nouvelle méthode 😉).

2023-03-14 09:54 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +            for (String competence : competencesInDomain.getValue()) {
Attention à la nomenclature.
Si je fais de la lecture rapide, j'imagine que "competence" c'est un objet contenant tous les paramètres relatifs à cet objet, or là il semble que c'est un string, donc j'imagine que c'est un competenceProportion plutôt (en analysant) ?

2023-03-14 09:54 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +
met ça dans une autre fonction

2023-03-14 09:54 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                    .add(Field.ORDREPERIODE, isNotNull(ordre) ? ordre.toString() : null).add(Field.SCORES, String.valueOf(scores))
avec le recul, scores => showScores / skills => showSkills (pour bien appuyer sur le fait que ce sont des booléens)

2023-03-14 13:56 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                                Map<String, JsonObject> competencesMap = extractData(competencesJson, ID_KEY);
java.lang.NullPointerException
	at fr.openent.competences.Utils.extractData(Utils.java:1001)
	at fr.openent.competences.service.impl.DefaultExportService.lambda$null$43(DefaultExportService.java:2030)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.CompositeFutureImpl.doComplete(CompositeFutureImpl.java:251)
	at io.vertx.core.impl.CompositeFutureImpl.tryFail(CompositeFutureImpl.java:236)
pour une période T1

2023-03-14 14:13 UTC, lapeyronnie commented on src/main/resources/i18n/en.json
> +	"evaluations.class.report.scores.and.skills": "Scores and skills"
espace à spprimer

2023-03-15 08:51 UTC, JinDouang commented
avec @qpic-cgi et @FlorentMr on retravaille sa PR

2023-03-20 14:03 UTC, qpic-cgi requested changes

2023-03-21 10:36 UTC, qpic-cgi approved these changes

2023-03-21 12:57 UTC, lapeyronnie approved these changes

2023-03-22 07:42 UTC, lapeyronnie commented on gradle.properties
> +entCoreVersion=4.9-SNAPSHOT
non, car il y a bien eu cette montée de version entre temps.

2023-03-22 07:48 UTC, merged

2023-03-22 08:18 UTC, qpic-cgi commented on gradle.properties
> +entCoreVersion=4.9-SNAPSHOT
Si, ça ne doit pas être fait dans cette PR.
il faut faire un commit approprié (chore() prepare for next development iteration, par exemple).