fix(suivi): EVAL-476 domaine and enseignement suivi classe et suivi eleve
OPEN-ENT-NG/competences pull request #221
Opened 2023-04-04 12:53 UTC by lapeyronnie

## Describe your changes
ajout de booléen ou réctification des conditions et pour le suivi classe, séparation des calculs pour ce cas
## Checklist tests
voir le tickets si join
## Issue ticket number and link
[EVAL-476](https://jira.support-ent.fr/browse/EVAL-476)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-04 14:04 UTC, lapeyronnie commented on src/main/resources/public/ts/models/teacher/Utils.ts
> -                }
déplacé dans la méthode setCompetenceEvaluations de la classe Utils.ts car cela n'est fait que pour le suivi Classe

2023-04-04 14:06 UTC, lapeyronnie commented on src/main/resources/public/ts/models/teacher/Utils.ts
>          //all evaluations
cette méthode n'est plus utilisée pour le suivi Classe

2023-04-04 14:09 UTC, FlorentMr requested changes

2023-04-04 14:09 UTC, FlorentMr commented on src/main/resources/public/ts/directives/teachingsSkills.ts
> +            $scope.isClasse = $scope.isClasse
Qu'est ce que fait cette ligne?

2023-04-04 14:09 UTC, FlorentMr commented on src/main/resources/public/ts/models/teacher/Utils.ts
> +                        if(competence.mineCompetencesEvaluations === undefined
if(competence.mineCompetencesEvaluations == null) est plus concis que (competence.mineCompetencesEvaluations === undefined || competence.mineCompetencesEvaluations === null) et fait la même chose

2023-04-04 14:09 UTC, FlorentMr commented on src/main/resources/public/ts/models/teacher/Utils.ts
> +                        if(competence.competencesEvaluations === undefined
if(competence.competencesEvaluations == null) est plus concis que (competence.competencesEvaluations === undefined || competence.competencesEvaluations === null) et fait la même chose

2023-04-05 07:09 UTC, lapeyronnie commented on src/main/resources/public/ts/directives/ProportionSuiviCompetence.ts
> +            $scope.isClasse = $scope.isClasse; //isClasse true suivi classe false suivi eleve
non commentaire, laissé exprès quand isClasse est true , on est dans le cas du suivi classe false suivi eleve. Je n'ai pas changé le nom de cette variable car elle est utilisée sur plusieurs HTML et méthode.

2023-04-05 08:13 UTC, lapeyronnie commented on src/main/resources/public/ts/directives/ProportionSuiviCompetence.ts
> -
plus nécessaire car coorectement set sur tous les HTML

2023-04-05 08:14 UTC, lapeyronnie commented on src/main/resources/public/ts/models/teacher/Utils.ts
> -                }
déplacé dans la méthode setCompetenceEvaluations de la classe Utils.ts car cela n'est fait que pour le suivi Classe

2023-04-05 08:39 UTC, FlorentMr approved these changes

2023-04-05 15:25 UTC, merged