feat(): #EVAL-339 add skills validated percentage in class council
OPEN-ENT-NG/competences pull request #223
Opened 2023-04-17 12:14 UTC by qpic-cgi

## Describe your changes
Sur la page du conseil de classe, affiche désormais le pourcentage de validation des compétences par enseignements.
- seules les compétences évalués comptes.
- les compétences validés: 3/4 ou 4/4.
- ne tiens pas compte de la surcharge d'un enseignement.

## Checklist tests
- Aller sur la page du conseil de classe.
- Si ce n'est pas déjà fait, checker l'option "Comp. validées (%)" des options du tableau (bouton  bleu avec flèche).
- Observer les différents pourcentages.

## Issue ticket number and link
[Jira - EVAL-339](https://jira.support-ent.fr/browse/EVAL-339)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-17 12:31 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java
> -                                      Handler<Either<String, JsonArray>> eitherHandler){
start indent

2023-04-17 12:33 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultBilanPerioqueService.java
> +                new DefaultNoteService(Competences.COMPETENCES_SCHEMA, Competences.NOTES_TABLE, eb)
end indent

2023-04-17 12:33 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultStructureOptions.java
> -    public void activeDeactiveSyncStatePresences(String idStructure, Boolean state, Handler<Either<String, JsonObject>> eitherHandler){
start indent

2023-04-17 12:34 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultStructureOptions.java
> +    private void isStructureActivatePresences(String idStructure, Handler<Either<String, JsonObject>> eitherHandler) {
end indent

2023-04-17 12:36 UTC, qpic-cgi commented on src/main/resources/public/ts/models/teacher/SuiviDesAcquis.ts
> -                    if(suiviDesAcquis.appreciations !== null && suiviDesAcquis.appreciations !== undefined){
start indent

2023-04-17 12:36 UTC, qpic-cgi commented on src/main/resources/public/ts/models/teacher/SuiviDesAcquis.ts
> +        return (moy === undefined) ? getNN() : moy;
end indent

2023-04-17 12:36 UTC, qpic-cgi commented on src/main/resources/public/ts/models/teacher/SuiviDesAcquis.ts
> -export class SuivisDesAcquis extends Model{
start indent

2023-04-17 12:37 UTC, qpic-cgi commented on src/main/resources/public/ts/models/teacher/SuiviDesAcquis.ts
> -    async getSuivisDesAcquis(){
end indent

2023-04-24 12:26 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/model/achievements/SubjectAchievements.java
> +    }
badge ?

2023-04-25 06:32 UTC, lapeyronnie requested changes

2023-04-25 13:46 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/Competences.java
cela devrait être plutôt dans la classe field, non ?

2023-04-26 14:31 UTC, merged