feat(class-report): #EVAL-227 add summaries at students averages pdf export
OPEN-ENT-NG/competences pull request #237
Opened 2023-05-22 13:55 UTC by qpic-cgi

## Describe your changes
Ajout (optionnel) de la synthèse sur l'exporte pdf des moyennes des élèves d'une classe. 

## Checklist tests
- En tant que Ce, sur la page "Suivi Classe"
- Après sélection d'une classe et d'une période, cliquer sur l'icone de téléchargement
- (Au moins un élève de la classe doit avoir une synthèse remplie pour la période sélectionnée)
- Dans la rubrique "Exporter au format PDF", sélectionner "Tableau des moyennes des élèves de la classe"
- Cliquer sur exporter
- observer l'ajoute des synthèses de chaque élèves

## Issue ticket number and link
[Jira - EVAL-227](https://jira.support-ent.fr/browse/EVAL-227)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-05-22 13:57 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
>      @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
End indent

2023-05-23 08:06 UTC, JinDouang requested changes
Au niveau de mes commentaires sur l'usage du cast et stream : 
Le fait que tu n'aimerais potentiellement pas filtrer les mauvais "data" pour forcer les exceptions au niveau de ta collection 

Dans ce cas si ce n'est pas envisageable pour ton flow, est-ce quand même possible de gérer ces cas en try catch afin que l'API puisse quand même répondre avec une erreur et non garder une exception unhandled

Car le risque de gérer en cast, ça créer une vulnérabilité au niveau du code ce qui peut amener à un exception => ok mais dans ce cas faudra bien les gérer derrière pour que l'API puisse répondre (avec un fail)

2023-05-23 08:06 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultAverageService.java
> +                                            .collect(Collectors.toList())))));
Afin d'enlever l'annotation warning et de "tricher" avec des cast unchecked : 

```suggestion
     result.getJsonArray(Field.ELEVES, new JsonArray())
                    .stream()
                    .filter(JsonObject .class::isInstance)
                    .map(JsonObject.class::cast)
                    .forEach(eleve -> eleve.put(Field.ELEVEMOYBYMAT,
                            Utils.sortJsonArrayIntValue(Field.RANK,
                                    new JsonArray(eleve.getJsonArray(Field.ELEVEMOYBYMAT, new JsonArray())
                                            .stream()
                                            .filter(JsonObject .class::isInstance)
                                            .map(JsonObject.class::cast)
                                            .map(eleveMoy -> eleveMoy.put(Field.RANK, subjectsEvaluated
                                                    .getJsonArray(Field.MATIERES, new JsonArray())
                                                    .stream()
                                                    .filter(JsonObject .class::isInstance)
                                                    .map(JsonObject.class::cast)
                                                    .filter(matiere -> eleveMoy.getString(Field.ID_MATIERE).equals(matiere.getString(Field.ID)))
                                                    .findFirst()
                                                    .map(matiere -> matiere.getInteger(Field.RANK, 0))
                                                    .orElse(0))
                                            )
                                            .collect(Collectors.toList())))));
```

2023-05-23 08:06 UTC, JinDouang commented on src/main/java/fr/openent/competences/service/impl/DefaultAverageService.java
> +            summaries.forEach(summary -> ((List<JsonObject>) result.getJsonArray(Field.ELEVES, new JsonArray()).getList())
Même principe qu'au-dessus (suggestion)

2023-05-23 08:16 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultAverageService.java
> +                                    .collect(Collectors.toList());
Ouai je connais bien ce tricks. Après trouvant ça "verbeux" pour un truc qui n'est de base pas super propre, j'ai tendance à ne pas m'en servir (On en a déjà discuté avec Bastien).
Mais ça me va carrément, je modifie

2023-05-23 10:11 UTC, JinDouang approved these changes

2023-05-23 13:55 UTC, BastienBenard commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
> +        this.storage = serviceFactory.storage();
Meme si c'était comme cela avant, tu peut maintenant utiliser ton servcies factory pour récupéré tes instances

2023-05-24 07:55 UTC, BastienBenard approved these changes

2023-05-24 09:16 UTC, merged