fix(deletedStudent) : #Eval 537 no students deleted in the select tags for student following and the class council
OPEN-ENT-NG/competences pull request #249
Opened 2023-06-29 14:25 UTC by lapeyronnie

## Describe your changes
Prise en compte des élèves supprimés sur le suivi élève et conseil de classe
## Checklist tests
Vérifier la présence des élèves supprimés dans les select des pages suivi éléve (élève en rouge) et conseil de classe.
Vérifier le passage de suivi classe au suivi élève : l'élève est bien selectionné
Vérifier que les élèves supprimés soient toujours en rouge dans le bilan périodique et la saisie des notes
## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-04 09:48 UTC, Gregprod33 requested changes

2023-07-04 09:48 UTC, Gregprod33 commented on src/main/resources/public/ts/controllers/eval_suivi_eleve_ctl.ts
> +            $scope.search.eleve = $scope.search.eleve = !!$scope.filteredEleves ? [...$scope.filteredEleves.all]
$scope.search.eleve = $scope.search.eleve

2023-07-04 09:48 UTC, Gregprod33 commented on src/main/resources/public/template/enseignants/bilan_periodique/display_bilan_periodique.html
> +                        <span ng-class="{'deletedStudent': informations.eleve.deleteDate !== null}">
!!informations.eleve.deleteDate, c'est la même chose ?

2023-07-04 13:17 UTC, lapeyronnie commented on src/main/resources/public/template/enseignants/bilan_periodique/display_bilan_periodique.html
> +                        <span ng-class="{'deletedStudent': informations.eleve.deleteDate !== null}">
bien vu

2023-07-05 09:06 UTC, Gregprod33 approved these changes

2023-07-05 09:26 UTC, qperie approved these changes

2023-07-05 12:36 UTC, merged