fix(SuiviClass_teacherAppraisals ) : #EVAL-545 not providing class averages for the year
OPEN-ENT-NG/competences pull request #270
Opened 2023-09-12 18:34 UTC by lapeyronnie

## Describe your changes
refactor : future convert to promise, change of the algorithmic logic to have the coefficients of the subtopics
## Checklist tests
suivi classe -> onglet appréciation voir le ticket ci-dessous
## Issue ticket number and link
[EVAL-545](https://jira.support-ent.fr/browse/EVAL-545)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-09-13 07:39 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/service/impl/DefaultExportBulletinService.java
> -    private void getElevesClasse( String idClasse, Long idPeriode, Future<JsonArray> elevesFuture){
supprimer car non utilisé

2023-09-18 14:38 UTC, qpic-cgi requested changes

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/Utils.java
> +                handlerToAsyncHandler(message -> {
utilise cette méthode plutôt:
https://github.com/OPEN-ENT-NG/competences/blob/dev/src/main/java/fr/openent/competences/helpers/FutureHelper.java#L83C31-L83C38

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/Utils.java
> +        eb.request(Competences.VIESCO_BUS_ADDRESS, action, handlerToAsyncHandler(new Handler<Message<JsonObject>>() {
utilise cette méthode plutôt:
https://github.com/OPEN-ENT-NG/competences/blob/dev/src/main/java/fr/openent/competences/helpers/FutureHelper.java#L83C31-L83C38

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/helpers/UtilsHelper.java
> +    public static Future<Void> completeVariablesForServices(Future<JsonArray> servicesFuture,
tu te sers où de ça ?
si tu ne l'utilises pas, tu peux supprimer.

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultClassAppreciation.java
> +                    });
Non !
Le résultat de chacune de tes futures doivent être traités qu'à partir de la ligne 177.
si tu tiens à faire comme ça , met chacune de tes futures dans une autre méthode !

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/java/fr/openent/competences/service/impl/DefaultClassAppreciation.java
> +                    }
Non !
CF commentaire sur le compose d'au dessus.

2023-09-18 14:38 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/eval_suivi_competences_classe_ctl.ts
> +
tu ne peux pas typer le retour de ces 2 fonctions ?

2023-09-25 15:53 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/Utils.java
> +        eb.request(Competences.VIESCO_BUS_ADDRESS, action, handlerToAsyncHandler(new Handler<Message<JsonObject>>() {
Je n'ai pas aplliqué la méthode proposée car dans ce cas on transforme la réponse

2023-09-25 15:54 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/helpers/UtilsHelper.java
> +    public static Future<Void> completeVariablesForServices(Future<JsonArray> servicesFuture,
Je m'en sers dans DefaultClassAppreciation et DefaultDevoirService

2023-09-29 09:37 UTC, qpic-cgi approved these changes

2023-09-29 11:53 UTC, merged