fix(ExportBulletin): EVAL-187 Reworked the cycle compétences PDF so it...
OPEN-ENT-NG/competences pull request #63
Opened 2022-03-22 13:59 UTC by FlorentMr

... looks the same as its front page in suivi élève / suivi classe, with notes by year in the cycle, with the last year being detailled by trimester/semester.

2022-03-30 07:05 UTC, lapeyronnie commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +            ($scope.releveComp.periode.libelle  === "cycle") ? url += "&isCycle=" + true : "&isCycle=" + false;
Pourquoi ne pas prendre search.periode ?

2022-03-30 07:05 UTC, lapeyronnie commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +            await httpAxios.get(url, {responseType: 'arraybuffer' })
Dans url, il manque id_cycle : on peut faire l'export sur les deux cycles.
Rappel : id_cycle = 1 cycle4 3/4/5 ème et id_cycle = 2 cycle 3 6 ème

2022-03-30 07:11 UTC, lapeyronnie commented
L'export pour un élève fonctionne bien le rendu est celui attendu. Il faut juste tenir compte du cycle sélectionné.
Pour l'export d'une classe, il y a une erreur : 
 2022-03-30 06:48:01 SEVERE Unhandled exception
java.lang.NullPointerException
	at fr.openent.competences.service.impl.DefaultExportService.calculPeriodesAnnees(DefaultExportService.java:872)
	at fr.openent.competences.service.impl.DefaultExportService.formatJsonObjectExportReleveComp(DefaultExportService.java:941)
	at fr.openent.competences.service.impl.DefaultExportService.access$200(DefaultExportService.java:77)
	at fr.openent.competences.service.impl.DefaultExportService$5.handle(DefaultExportService.java:841)
	at fr.openent.competences.service.impl.DefaultExportService$5.handle(DefaultExportService.java:782)
	at fr.openent.competences.service.impl.DefaultExportService$2.handle(DefaultExportService.java:705)
	at fr.openent.competences.service.impl.DefaultExportService$2.handle(DefaultExportService.java:692)
	at fr.openent.competences.service.impl.DefaultExportService$4.handle(DefaultExportService.java:747)
	at fr.openent.competences.service.impl.DefaultExportService$4.handle(DefaultExportService.java:732)
	at org.entcore.comm

2022-05-10 14:13 UTC, lapeyronnie commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
>          final List<String> listIdMatieres = request.params().getAll("idMatiere");
a mettre dans le try catch qu'il y a un peu plus bas

2022-05-12 13:53 UTC, Rseuret requested changes

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultCompetencesService.java
> +    public void getDevoirCompetences(Long devoirId, Long idCycle, final Handler<Either<String, JsonArray>> handler) {
vu les impacts ce n aurait pas été mieux de faire : 
getDevoirCompetences(Long devoirId, final Handler<Either<String, JsonArray>> handler){
getDevoirCompetences(devoirId, null,handler); 
}
Afin de limiter l impact ?

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
> +        if(eleveLevelString != null){
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
> +        else{
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +            else if (idCycle == 2){
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                if(i <= debut && i >= fin){
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +        if(idCycle != null){
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/java/fr/openent/competences/service/impl/DefaultExportService.java
> +                        if(Objects.equals(Integer.parseInt(classe.substring(0, 1)), eleveLevel)){
indentation

2022-05-12 13:53 UTC, Rseuret commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +                    url += "&idMatiere=" + $scope.selected.matieres[m];
on risque pas d avoir une taille max atteinte d url?

2022-05-23 08:41 UTC, FlorentMr commented on src/main/java/fr/openent/competences/controllers/ExportPDFController.java
>          final List<String> listIdMatieres = request.params().getAll("idMatiere");
Ce n'est pas un paramètre obligatoire car si il n'est pas présent dans la liste des paramètres de la requête, on lui assigne null (et on ne peut pas donner null comme valeur en appelant une API)

2022-05-23 08:49 UTC, FlorentMr commented on src/main/java/fr/openent/competences/service/impl/DefaultCompetencesService.java
> +    public void getDevoirCompetences(Long devoirId, Long idCycle, final Handler<Either<String, JsonArray>> handler) {
Effectivement le polymorphisme aurait été plus rapide à faire, maintenant que le changement est fait cependant, tout revert pour le mettre en place n'est pas necessaire (discuté avec Remy)

2022-05-23 08:51 UTC, FlorentMr commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +                    url += "&idMatiere=" + $scope.selected.matieres[m];
Le changement ne change pas la taille max de l'URL dans le cas le plus long, et on a jamais eu de problème lié à ça depuis, à garder en tête mais normalement pas de problèmes ne devraient en découler

2022-05-30 13:17 UTC, lapeyronnie approved these changes

2022-05-30 13:22 UTC, merged