fix(RelevePeriodique): EVAL-314 Fixed evaluation suppression possible for teachers even if the evaluation was outdated
OPEN-ENT-NG/competences pull request #78
Opened 2022-05-06 12:27 UTC by FlorentMr

2022-05-17 07:12 UTC, Rseuret requested changes

2022-05-17 07:12 UTC, Rseuret commented on src/main/resources/public/template/enseignants/informations/display_devoir.html
> +    <lightbox id="delete-periodic" ng-if="selected.devoirs.list.length == 1 || devoirsUncancelable.length == 1" show="opened.evaluation.suppressionMsg2" on-close="opened.evaluation.suppressionMsg2=fa
utilise plutot le ===

2022-05-17 07:12 UTC, Rseuret commented on src/main/resources/public/template/enseignants/informations/display_devoir.html
> +            <span ng-if="(selected.devoirs.list.length + devoirsUncancelable.length)>= 12"
utiliser le >==

2022-05-20 07:02 UTC, lapeyronnie commented on src/main/resources/public/template/enseignants/informations/display_devoir.html
> +        <p ng-if="devoirsUncancelable.length > 0 ">
Changement de stratégie : pour un professeur, ne pas faire apparître le bouton supprimé si la période est dépasser.

2022-05-20 07:55 UTC, lapeyronnie commented on src/main/resources/public/ts/controllers/eval_teacher_ctl.ts
> +                    $scope.informations.devoir.endSaisie = await $scope.checkEndSaisieSeul($scope.informations.devoir);
1. Vérifie ce que la méthode 'checkEndSaisieSeul' retourne, car actuellement on a la comprotement inverse de ce qui est demandé
2. Par rapport, aux régles de gestion, de cette page : les ce ont le droit de pourvoir tout faire en dehors de la période en cours et le professeur seuleemnt pour la période en cours, il vaut utiliser cette méthode 'checkEndSaisie' (elle était dans firstConfirmationSuppDevoir

2022-05-24 14:43 UTC, merged